[package]
name = "trias_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", features = ["stream"] }

tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
tokio-util = { version = "0.7", features = ["io", "io-util"] }

dotenv = "0.15"
chrono = "0.4.42"
enum-assoc = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.37", features = ["serialize", "async-tokio"] }
